{"timestamp": "2025-10-17T22:06:42.894049Z", "level": "ERROR", "logger": "__main__", "message": "Mensagem de erro", "process_id": 13820, "thread_name": "MainThread", "filename": "test_logging_json.py", "line_number": 46, "function": "test_basic_logging"}
{"timestamp": "2025-10-17T22:06:42.905049Z", "level": "ERROR", "logger": "__main__", "message": "Erro ao executar operação matemática", "process_id": 13820, "thread_name": "MainThread", "filename": "logging_config.py", "line_number": 328, "function": "log_with_context", "operation": "division", "numerator": 10, "denominator": 0, "exc_info": true}
{"timestamp": "2025-10-17T22:06:42.907050Z", "level": "ERROR", "logger": "__main__", "message": "Exceção capturada", "process_id": 13820, "thread_name": "MainThread", "filename": "test_logging_json.py", "line_number": 127, "function": "test_exception_logging", "exception": {"type": "ZeroDivisionError", "message": "division by zero", "traceback": "Traceback (most recent call last):\n  File \"C:\\workstashion\\eda-aiminds-i2a2-rb\\tests\\utils\\test_logging_json.py\", line 116, in test_exception_logging\n    result = 10 / 0\n             ~~~^~~\nZeroDivisionError: division by zero"}}
